name: Test

on: [pull_request]

jobs:
  assets:
    name: Assets
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Get Cache Directory
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: |
          composer install -q --no-interaction
          bun install --silent

      - name: Get Bun Cache Directory
        id: bun-cache-dir
        run: echo dir=$(bun pm cache) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: bun-cache-${{ hashFiles('**/bun.lockb') }}
          path: ${{ steps.bun-cache-dir.outputs.dir }}
          restore-keys: bun-cache-

      - name: Install Dependencies
        run: bun install --silent

      - name: Build Assets
        run: bun run build

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Get Cache Directory
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: |
          composer install -q --no-interaction
          bun install --silent

      - name: Configure Application
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Run Rector
        run: composer rector --dry-run

      - name: Run Linter
        run: composer lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2

      - name: Get Cache Directory
        id: composer-cache-dir
        run: echo dir=$(composer config cache-files-dir) >> $GITHUB_OUTPUT

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: composer-cache-${{ hashFiles('**/composer.lock') }}
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          restore-keys: composer-cache-

      - name: Install Dependencies
        run: |
          composer install -q --no-interaction
          bun install --silent

      - name: Configure Application
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Run Tests
        run: composer test
